# # # # # # # # # # # # #
#   K i k o - p l u s   #
# # # # # # # # # # # # #

# Basic
name:               "The more I learn, the more I realize how much I do not know"

author:
#  facebook:         your-id
#  youtubeUser:      your-id
#  youtubeChannel:   your-id
#  twitter:          your-id
  github:           https://github.com/yoonkiss
#  stackoverflow:    your-id
#  quora:            your-id
#  linkedin:         your-id
#  pinterest:        your-id
#  googlePlus:       your-id
#  instagram:        your-id
#  reddit:           your-id
#  medium:           your-id
#  tumblr:           your-id
#  email:            your-id@your-email.com

copyright:
  year:             2017
  name:             yoonkiss

# Google-analytics
google-analytics:
  id:               "UA-36718219-2"
google_ad: "ca-pub-8806842758252812"

# Disqus
disqus:
  id:               "yoonkiss"

# URL
url:                "https://yoonkiss.github.io" # the base hostname & protocol for your site
# url:                "http://localhost:4000" # use this url when you develop
baseurl:            "" # the subpath of your site, e.g. /blog


# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:           Asia/Seoul
permalink:          /:year-:month-:day/:title/

# Pagination
paginate:           5
paginate_path:      /page:num/

# Markdown
markdown:           kramdown
kramdown:
  input:            GFM

# Navigation
nav:
#  - name:           "About"
#    url:            "/about"
  - name:           "Home"
    url:            "/"
  - name:           "Archive"
    url:            "/archive"
  - name:           "Tags"
    url:            "/tags"
#  - name:           "Github"
#    url:            "https://github.com/yoonkiss"

# Sass
sass:
  sass_dir:         _sass
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-admin

exclude:            [vendor]